### ISSUE TITLE
Do i have access to the meson branch?

### ISSUE THREAD

**Issue by SolarAquarion** [highperformancecoder/classdesc#2]

**Comment by highperformancecoder** [comment]
You should be able to pull request to it.

I'm not sure how to set up write access to that branch alone, so PR
may be the best way for now.

Cheers

On Sun, Nov 26, 2017 at 11:38:53PM +0000, SolarAquarion wrote:
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/classdesc/issues/2

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by SolarAquarion** [comment]
okay then

**Comment by SolarAquarion** [comment]
ccache c++  -o src/classdesc 'src/classdesc@exe/classdesc.cc.o' 'src/classdesc@exe/insert-friend.cc.o' 'src/classdesc@exe/xdr_pack.cc.o' -Wl,--no-undefined -Wl,--as-needed  
src/classdesc@exe/insert-friend.cc.o: In function `std::_Rb_tree_key_compare<std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rb_tree_key_compare()':
/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:238: multiple definition of `tokeninput::operator=(tokeninput::mark_t&)'
src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:238: first defined here
src/classdesc@exe/insert-friend.cc.o: In function `tokeninput::operator>(tokeninput::mark_t&)':
/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:248: multiple definition of `tokeninput::operator>(tokeninput::mark_t&)'
src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:248: first defined here
src/classdesc@exe/insert-friend.cc.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:263: multiple definition of `gobble_delimited[abi:cxx11](tokeninput&, char const*, char const*)'
src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:263: first defined here
src/classdesc@exe/insert-friend.cc.o: In function `get_template_args[abi:cxx11](tokeninput&)':
/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:285: multiple definition of `get_template_args[abi:cxx11](tokeninput&)'
src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:285: first defined here
src/classdesc@exe/insert-friend.cc.o: In function `extract_targs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
/home/solaraquarion/classdesc/builddir/../src/insert-friend.cc:32: multiple definition of `extract_targs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/classdesc.cc:727: first defined here
src/classdesc@exe/insert-friend.cc.o: In function `main':
/home/solaraquarion/classdesc/builddir/../src/insert-friend.cc:136: multiple definition of `main'
src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/classdesc.cc:862: first defined here

i got my first build fail

**Comment by highperformancecoder** [comment]
These objects should not be linked together.

On Mon, Nov 27, 2017 at 01:53:38AM +0000, SolarAquarion wrote:
> ccache c++  -o src/classdesc 'src/classdesc@exe/classdesc.cc.o' 'src/classdesc@exe/insert-friend.cc.o' 'src/classdesc@exe/xdr_pack.cc.o' -Wl,--no-undefined -Wl,--as-needed  
> src/classdesc@exe/insert-friend.cc.o: In function `std::_Rb_tree_key_compare<std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_Rb_tree_key_compare()':
> /home/solaraquarion/classdesc/builddir/../src/tokeninput.h:238: multiple definition of `tokeninput::operator=(tokeninput::mark_t&)'
> src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:238: first defined here
> src/classdesc@exe/insert-friend.cc.o: In function `tokeninput::operator>(tokeninput::mark_t&)':
> /home/solaraquarion/classdesc/builddir/../src/tokeninput.h:248: multiple definition of `tokeninput::operator>(tokeninput::mark_t&)'
> src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:248: first defined here
> src/classdesc@exe/insert-friend.cc.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > std::operator+<char, std::char_traits<char>, std::allocator<char> >(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
> /home/solaraquarion/classdesc/builddir/../src/tokeninput.h:263: multiple definition of `gobble_delimited[abi:cxx11](tokeninput&, char const*, char const*)'
> src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:263: first defined here
> src/classdesc@exe/insert-friend.cc.o: In function `get_template_args[abi:cxx11](tokeninput&)':
> /home/solaraquarion/classdesc/builddir/../src/tokeninput.h:285: multiple definition of `get_template_args[abi:cxx11](tokeninput&)'
> src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/tokeninput.h:285: first defined here
> src/classdesc@exe/insert-friend.cc.o: In function `extract_targs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
> /home/solaraquarion/classdesc/builddir/../src/insert-friend.cc:32: multiple definition of `extract_targs(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
> src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/classdesc.cc:727: first defined here
> src/classdesc@exe/insert-friend.cc.o: In function `main':
> /home/solaraquarion/classdesc/builddir/../src/insert-friend.cc:136: multiple definition of `main'
> src/classdesc@exe/classdesc.cc.o:/home/solaraquarion/classdesc/builddir/../src/classdesc.cc:862: first defined here
> 
> i got my first build fail
> 
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/highperformancecoder/classdesc/issues/2#issuecomment-347059053

-- 

----------------------------------------------------------------------------
Dr Russell Standish                    Phone 0425 253119 (mobile)
Principal, High Performance Coders
Visiting Senior Research Fellow        hpcoder@hpcoders.com.au
Economics, Kingston University         http://www.hpcoders.com.au
----------------------------------------------------------------------------

**Comment by SolarAquarion** [comment]
i guess i need to modify the meson.build to be more sane?

**Comment by SolarAquarion** [comment]
odd

**Comment by SolarAquarion** [comment]
I'm an idiot
